description: LttP Race # Used to describe your yaml. Useful if you have multiple files
name: Hyrule # Your name in-game. Spaces will be replaced with underscores and there is a 16 character limit

game:
  A Link to the Past: 1
requires:
  version: 0.1.7 # Version of Archipelago required for this yaml to work as expected.
# Shared Options supported by all games:
accessibility:
  items: 0 # Guarantees you will be able to acquire all items, but you may not be able to access all locations
  locations: 50 # Guarantees you will be able to access all locations, and therefore all items
  none: 0 # Guarantees only that the game is beatable. You may not be able to access all locations or acquire all items
progression_balancing:
  on: 50 # A system to reduce BK, as in times during which you can't do anything by moving your items into an earlier access sphere to make it likely you have stuff to do
  off: 0 # Turn this off if you don't mind a longer multiworld, or can glitch/sequence break around missing items.
A Link to the Past:
  ### Logic Section ###
  glitches_required: # Determine the logic required to complete the seed
    none: 50 # No glitches required
    minor_glitches: 0 # Puts fake flipper, waterwalk, super bunny shenanigans, and etc into logic
    overworld_glitches: 0 # Assumes the player has knowledge of both overworld major glitches (boots clips, mirror clips) and minor glitches
    hybrid_major_glitches: 0 # In addition to overworld glitches, also requires underworld clips between dungeons.
    no_logic: 0 # Your own items are placed with no regard to any logic; such as your Fire Rod can be on your Trinexx.
    # Other players items are placed into your world under HMG logic
  dark_room_logic: # Logic for unlit dark rooms
    lamp: 50 # require the Lamp for these rooms to be considered accessible.
    torches: 0 # in addition to lamp, allow the fire rod and presence of easily accessible torches for access
    none: 0 # all dark rooms are always considered doable, meaning this may force completion of rooms in complete darkness
  ### End of Logic Section ###
  legacy_dungeon_items:
    mc: 10 # Shuffle maps and compasses
    none: 50 # Shuffle none of the 4
    lmcsb: 10 # Like mcsb above, but with keys kept local to your world. l is what makes your keys local, or not if it's missing
  compass_shuffle: original_dungeon
  map_shuffle: original_dungeon
  bigkey_shuffle: original_dungeon
  smallkey_shuffle: original_dungeon
  dungeon_counters:
    on: 0 # Always display amount of items checked in a dungeon
    pickup: 50 # Show when compass is picked up
    default: 0 # Show when compass is picked up if the compass itself is shuffled
    off: 0 # Never show item count in dungeons
  entrance_shuffle:
    none: 50 # Vanilla game map. All entrances and exits lead to their original locations. You probably want this option
    dungeonssimple: 0 # Shuffle just dungeons amongst each other, swapping dungeons entirely, so Hyrule Castle is always 1 dungeon
    dungeonsfull: 25 # Shuffle any dungeon entrance with any dungeon interior, so Hyrule Castle can be 4 different dungeons, but keep dungeons to a specific world
    dungeonscrossed: 0 # like dungeonsfull, but allow cross-world traversal through a dungeon. Warning: May force repeated dungeon traversal
    simple: 0 # Entrances are grouped together before being randomized. Simple uses the most strict grouping rules
    restricted: 0 # Less strict than simple
    full: 0 # Less strict than restricted
    crossed: 0 # Less strict than full
    insanity: 0 # Very few grouping rules. Good luck
  goals:
    ganon: 1 # Climb GT, defeat Agahnim 2, and then kill Ganon
    crystals: 10 # Only killing Ganon is required. However, items may still be placed in GT
    bosses: 0 # Defeat the boss of all dungeons, including Agahnim's tower and GT (Aga 2)
    pedestal: 1 # Pull the Triforce from the Master Sword pedestal
    ganon_pedestal: 1 # Pull the Master Sword pedestal, then kill Ganon
    triforce_hunt: 0 # Collect 20 of 30 Triforce pieces spread throughout the worlds, then turn them in to Murahadala in front of Hyrule Castle
    local_triforce_hunt: 0 # Collect 20 of 30 Triforce pieces spread throughout your world, then turn them in to Murahadala in front of Hyrule Castle
    ganon_triforce_hunt: 0 # Collect 20 of 30 Triforce pieces spread throughout the worlds, then kill Ganon
    local_ganon_triforce_hunt: 0 # Collect 20 of 30 Triforce pieces spread throughout your world, then kill Ganon
    ice_rod_hunt: 0 # You start with everything needed to 216 the seed. Find the Ice rod, then kill Trinexx at Turtle rock.
  open_pyramid:
    goal: 50 # Opens the pyramid if the goal requires you to kill Ganon, unless the goal is Slow Ganon or All Bosses
    auto: 0 # Same as Goal, but also is closed if holes are shuffled and ganon is part of the shuffle pool
    yes: 0 # Pyramid hole is always open. Ganon's vulnerable condition is still required before he can he hurt
    no: 0 # Pyramid hole is always closed until you defeat Agahnim atop Ganon's Tower
  crystals_needed_for_gt: # Crystals required to open GT
    0: 0
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
    random: 0
    random-low: 50 # any valid number, weighted towards the lower end
    random-middle: 0 # any valid number, weighted towards the central range
    random-high: 0 # any valid number, weighted towards the higher end
  crystals_needed_for_ganon: # Crystals required to hurt Ganon
    0: 0
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
    6: 0
    7: 0
    random: 0
    random-low: 0
    random-middle: 0
    random-high: 50
  mode:
    standard: 25 # Begin the game by rescuing Zelda from her cell and escorting her to the Sanctuary
    open: 50 # Begin the game from your choice of Link's House or the Sanctuary
    inverted: 25 # Begin in the Dark World. The Moon Pearl is required to avoid bunny-state in Light World, and the Light World game map is altered
  hints:
    'on': 50 # Hint tiles sometimes give item location hints
    'off': 0 # Hint tiles provide gameplay tips
  item_pool: normal
  item_functionality: normal
  boss_shuffle:
    none: 75 # Vanilla bosses
    basic: 0 # Existing bosses except Ganon and Agahnim are shuffled throughout dungeons
    full: 0 # 3 bosses can occur twice
    chaos: 0 # Any boss can appear any amount of times
    singularity: 25 # Picks a boss, tries to put it everywhere that works, if there's spaces remaining it picks a boss to fill those
  shop_item_slots: # Maximum amount of shop slots to be filled with regular item pool items (such as Moon Pearl)
    0: 50
    30: 10
  shop_shuffle: u # Shuffle capacity upgrades into the item pool (and allow them to traverse the multiworld)
triggers:
  - option_name: shop_item_slots
    option_result: 30
    option_category: A Link to the Past
    options:
      A Link to the Past:
        start_inventory:
          Rupees (300): 2
  - option_name: legacy_dungeon_items
    option_result: mc
    option_category: A Link to the Past
    options:
      A Link to the Past:
        compass_shuffle: any_world
        map_shuffle: any_world
  - option_name: legacy_dungeon_items
    option_result: lmcsb
    option_category: A Link to the Past
    options:
      A Link to the Past:
        compass_shuffle: own_world
        map_shuffle: own_world
        bigkey_shuffle: own_world
        smallkey_shuffle: own_world